name: flutter_platform_component
description: Ready-made inherited component base using ready-made abstractions for quick use and decomposed by platform.
version: 3.0.6
repository: https://github.com/ivangalkindeveloper/flutter_platform_component

environment:
  sdk: ">=2.18.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  animate_do: 3.1.2
  animations: 2.0.8
  badges: 3.1.2
  collection: ^1.17.2
  dotted_border: 2.1.0
  flutter:
    sdk: flutter
  flutter_vibrate: 1.3.0
  modal_bottom_sheet: 3.0.0-pre
  pinput: 3.0.1
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true